apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-controller-setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  namespace: nok-base
  image: ghcr.io/cspdevlabs/mcp-controller:1.0.2
  prometheus-url: http://prometheus-operated.nok-bng.svc.cluster.local:9090
  loki-url: http://tel-loki.nok-bng.svc.cluster.local:3100
  k8s-namespace: nok-bng
  mcp-environment: production
  ingress-host: mcp-bng.nok.local
