apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-controller-sa
  labels:
    app: mcp-controller
    app.kubernetes.io/app: mcp-controller
    app.kubernetes.io/component: mcp-controller
    app.kubernetes.io/name: mcp-controller
  namespace: nok-base
